name: Publish npm package
on:
  push:
    tags:
      - "v*"
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
        registry-url: 'https://npm.pkg.github.com'
        scope: '@rinkrank' # Replace with your GitHub username or organization name

    - name: Install dependencies
      run: npm ci
    - name: Prepare release
      run: npx release-it --ci --disable-metrics --no-git.requireUpstream --no-npm.publish --config=.release-it.json

    - name: Publish to GitHub Packages
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}